<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Lab 3: Handling of Biological Data in R - 1 – Biology 3315 Molecular Evolution and Phylogenetics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-lab4_biologicaldata2.html" rel="next">
<link href="./02-lab2_intro_to_R_pt2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b9eaee60a963b5d74e9d33cc267de6a6.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-aa873432a3c62897e6c2091c0d30a948.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-b9eaee60a963b5d74e9d33cc267de6a6.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-lab3_biological_data1.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><strong>Lab 3: Handling of Biological Data in R - 1</strong></span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Biology 3315 Molecular Evolution and Phylogenetics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/idohatam/Biol3315_lab_book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Biology 3315 Molecular Evolution and Phylogenetics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-lab1_intro_to_R_pt1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title"><strong>Lab 1: Introduction to the R Programming Language and the RStudio IDE</strong></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-lab2_intro_to_R_pt2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><strong>Lab 2: Data Manipulation and Presentation in R</strong></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-lab3_biological_data1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><strong>Lab 3: Handling of Biological Data in R - 1</strong></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-lab4_biologicaldata2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title"><strong>Lab 4: Handling of Biological Data in R - 2</strong></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-lab5_pop_gen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 5: Population Genetics and Selection</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-lab6_msa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 6: Sequence Evolution</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-lab7_trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title"><strong>Lab 7: Using Sequences to Reconstruct Phylogenetic Trees</strong></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-lab8_genome_trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title"><strong>Lab 8: Comparing Phylogenetic Trees Made with Genes and Genomes</strong></span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives"><span class="header-section-number">4.1</span> <strong>Learning objectives</strong></a></li>
  <li><a href="#lab3" id="toc-lab3" class="nav-link" data-scroll-target="#lab3"><span class="header-section-number">5</span> <strong>Lab3</strong></a>
  <ul>
  <li><a href="#installing-packages-from-bioconductor" id="toc-installing-packages-from-bioconductor" class="nav-link" data-scroll-target="#installing-packages-from-bioconductor"><span class="header-section-number">5.1</span> <strong>Installing packages from Bioconductor</strong></a></li>
  <li><a href="#working-with-sequences-using-base-r-and-the-tidyverse" id="toc-working-with-sequences-using-base-r-and-the-tidyverse" class="nav-link" data-scroll-target="#working-with-sequences-using-base-r-and-the-tidyverse"><span class="header-section-number">5.2</span> <strong>Working with sequences using base R and the tidyverse</strong></a></li>
  <li><a href="#biostrings" id="toc-biostrings" class="nav-link" data-scroll-target="#biostrings"><span class="header-section-number">5.3</span> <strong>Biostrings</strong></a></li>
  <li><a href="#seqinr" id="toc-seqinr" class="nav-link" data-scroll-target="#seqinr"><span class="header-section-number">5.4</span> <strong>seqinr</strong></a></li>
  <li><a href="#exporting-sequence-elements" id="toc-exporting-sequence-elements" class="nav-link" data-scroll-target="#exporting-sequence-elements"><span class="header-section-number">5.5</span> <strong>Exporting sequence elements</strong></a></li>
  </ul></li>
  <li><a href="#summary-exercise" id="toc-summary-exercise" class="nav-link" data-scroll-target="#summary-exercise"><span class="header-section-number">6</span> <strong>Summary exercise:</strong></a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/idohatam/Biol3315_lab_book/edit/main/03-lab3_biological_data1.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><strong>Lab 3: Handling of Biological Data in R - 1</strong></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><br></p>
<section id="learning-objectives" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">4.1</span> <strong>Learning objectives</strong></h2>
<details>
<summary>
Click to expand
</summary>
<p><strong>By the end of this lab you will be able to:</strong></p>
<ul>
<li><p>Demonstrate the ability to install packages from Bioconductor</p></li>
<li><p>Demonstrate the ability to import and export biological sequences</p></li>
<li><p>Demonstrate the ability to manipulate biological sequences using base R and tidyverse</p></li>
<li><p>Demonstrate the ability to collect basic statistics of biological sequences using base R</p></li>
<li><p>Demonstrate an understanding of the basic data classes of the Biostrings and seqinr packages</p></li>
<li><p>Demonstrate the ability to manipulate both multiple and single biological strings using tools from the Biostrings and seqinr packages</p></li>
<li><p>Demonstrate the ability to collect basic statistics of biological strings using tools from the Biostrings and seqinr packages</p></li>
</ul>
</details>
<hr>
</section>
<section id="lab3" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> <strong>Lab3</strong></h1>
<p>R has many tools for handling biological data. Over the next couple of labs, you will build the vocabulary needed to work with sequences, statistical methods and objects, trees, and dendrograms.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"vegan"</span>,<span class="st">"ape"</span>,<span class="st">"ade4"</span>,<span class="st">"ggdendro"</span>,<span class="st">"dendextend"</span>,<span class="st">"seqinr"</span>,<span class="st">"pvclust"</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># lapply is part of the apply family of functions, one of those functions that act as a for loop</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">lapply</span>(<span class="fu">c</span>(<span class="st">"vegan"</span>,<span class="st">"ape"</span>,<span class="st">"ade4"</span>,<span class="st">"ggdendro"</span>,<span class="st">"dendextend"</span>,<span class="st">"seqinr"</span>,<span class="st">"pvclust"</span>), </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>        library, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You should also load the tidyverse packages.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><br></p>
<section id="installing-packages-from-bioconductor" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="installing-packages-from-bioconductor"><span class="header-section-number">5.1</span> <strong>Installing packages from Bioconductor</strong></h2>
<p><a href="https://bioconductor.org/">Bioconductor</a> is a repository that stores R packages geared towards the analysis of biological data. Most packages in Bioconductor are designed to handle omics, cellular, genetic, and biochemical data, and thus will be more useful in more advanced courses. However, some of the packages on Bioconductor are excellent for this course. One of them is the Biostrings package, which, as its name suggests, handles biological strings (i.e., nucleotide and amino acid sequences). While there are packages on CRAN with similar functions, it is a good opportunity to familiarize yourself with the object structure employed by Bioconductor packages.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Bioconductor requires its own package manager</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">install.packages</span>(<span class="st">"BiocManager"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Once the manager is installed, you can install Bioconductor packages</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> BiocManager<span class="sc">::</span><span class="fu">install</span>(<span class="st">"Biostrings"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">library</span>(Biostrings)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that when you load the packages, functions can get masked. Make sure you are using the function from the correct package. You can do that by specifying the package when calling the function, e.g., <code>dplyr::summarise()</code>.</p>
<p><br></p>
</section>
<section id="working-with-sequences-using-base-r-and-the-tidyverse" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="working-with-sequences-using-base-r-and-the-tidyverse"><span class="header-section-number">5.2</span> <strong>Working with sequences using base R and the tidyverse</strong></h2>
<p>You were introduced to strings during lab 1, and biological strings are no different than regular strings. Nucleotide sequences are comprised of up to 20 nucleotide symbols (ATCG, U, and letters that denote alternative bases, base groups, and modified bases). Amino acid sequences are comprised of up to 28 symbols (the 20 standard amino acids plus special codes for ambiguity and modifications).</p>
<p>Base R and some functions from <code>stringr</code> make it easy to perform basic processing of biological strings. Let’s reexamine a simple example and create a string of 100 nucleotides.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Why am I setting seeds?</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">set.seed</span>(<span class="dv">649</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Generate a vector of nucleotides</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq1 <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"T"</span>,<span class="st">"C"</span>,<span class="st">"G"</span>), <span class="dv">100</span>, <span class="at">replace =</span> T), <span class="at">collapse =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Next, we can count how many times each nucleotide appears in the sequence using a simple <code>for</code> loop.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> nucs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"T"</span>,<span class="st">"C"</span>,<span class="st">"G"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> reps <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">4</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(nucs)) {</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   reps[i] <span class="ot">&lt;-</span> <span class="fu">str_count</span>(sq1, nucs[i])</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span> }</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(nucs, reps)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  nucs reps
1    A   24
2    T   17
3    C   29
4    G   30</code></pre>
</div>
</div>
<p>It is also simple to chart these counts.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> nucs, <span class="at">y =</span> reps)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-lab3_biological_data1_files/figure-html/plot sequence counts-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It is relatively simple to find start and stop codons (the first step in predicting ORFs).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># With the stringr package it is simple to find all start and stop codons</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> (atg <span class="ot">&lt;-</span> <span class="fu">str_locate_all</span>(sq1, <span class="st">"ATG"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
     start end
[1,]     5   7
[2,]    41  43</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Just one of the stop codons</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> (stp <span class="ot">&lt;-</span> <span class="fu">str_locate_all</span>(sq1, <span class="st">"TAA"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
     start end</code></pre>
</div>
</div>
<p>From here you can write a loop calculating the length of characters from the first nucleotide of each start codon to the last nucleotide of every stop codon. Those that are divisible by 3 represent open reading frames. We won’t implement this here. The <code>stringr</code> package also makes it easy to convert between DNA and RNA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># stringr also makes it easy to convert between DNA and RNA</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq1.rna <span class="ot">&lt;-</span> <span class="fu">str_replace_all</span>(sq1, <span class="st">"T"</span>, <span class="st">"U"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">str_sub</span>(sq1, <span class="dv">1</span>, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "GAAGATGTCT"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">str_sub</span>(sq1.rna, <span class="dv">1</span>, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "GAAGAUGUCU"</code></pre>
</div>
</div>
<hr>
<p><strong>Quick R exercise</strong></p>
<ol type="1">
<li>Write a function that takes a nucleotide string, summarizes the occurrence of each nucleotide into a table, and graphs it.</li>
</ol>
<hr>
<p>Next, let’s see how to convert a sequence of nucleotides to its reverse and complementary sequence.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># First let's generate a shorter sequence, it will be easier to inspect</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq2 <span class="ot">&lt;-</span> <span class="fu">str_sub</span>(sq1, <span class="dv">1</span>, <span class="dv">10</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># stringr doesn't have a good option to replace every base with its complement because it can only </span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># replace one pattern at a time.</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq2c <span class="ot">&lt;-</span> <span class="fu">str_replace_all</span>(sq2, <span class="st">"T"</span>, <span class="st">"A"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now that all Ts are As, there’s no way to replace all original As with Ts. It can be done by splitting the string into a character vector using <code>str_split</code> from <code>stringr</code>. Note the <code>[[]]</code> since <code>str_split</code> outputs a list.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> sq2c <span class="ot">&lt;-</span> <span class="fu">str_split</span>(sq2, <span class="st">""</span>)[[<span class="dv">1</span>]]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Now with a chain of ifelse it is possible to replace each position</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq2c <span class="ot">&lt;-</span> <span class="fu">if_else</span>(sq2c <span class="sc">==</span> <span class="st">"T"</span>, <span class="st">"A"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>                 <span class="fu">if_else</span>(sq2c <span class="sc">==</span> <span class="st">"A"</span>, <span class="st">"T"</span>, </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>                         <span class="fu">if_else</span>(sq2c <span class="sc">==</span> <span class="st">"G"</span>, <span class="st">"C"</span>, <span class="fu">if_else</span>(sq2c <span class="sc">==</span> <span class="st">"C"</span>, <span class="st">"G"</span>, sq2c))))</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Complementary, indeed.</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "GAAGATGTCT"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> sq2c</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "C" "T" "T" "C" "T" "A" "C" "A" "G" "A"</code></pre>
</div>
</div>
<p>We can now use the <code>rev</code> function to reverse the order of the vector, resulting in a sequence that is reverse and complementary.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> sq2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "GAAGATGTCT"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> sq2c</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "C" "T" "T" "C" "T" "A" "C" "A" "G" "A"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> (sq2rc <span class="ot">&lt;-</span> <span class="fu">rev</span>(sq2c))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "A" "G" "A" "C" "A" "T" "C" "T" "T" "C"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Is it possible to locate a codon using a vector?</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># First occurrence using str_locate</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">str_locate</span>(sq2c, <span class="st">"GTT"</span>)[<span class="dv">1</span>,]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>start   end 
   NA    NA </code></pre>
</div>
</div>
<p>In order to find the codon, we need to find all occurrences of the nucleotide G, and then find which nucleotides are found one and two positions over. Not impossible but definitely annoying. An easier way would be to convert the vector back to a string and match patterns.</p>
<hr>
<p><strong>Quick R exercise</strong></p>
<p>We will need to convert sequences to reverse complement again. Based on the code snippet above, write a function that does so. Name it rev_comp.</p>
<hr>
<p>Converting a string to its reverse and complement sequence adds a level of complexity because of the switch between strings to character vectors and back. This doesn’t look too complex, but as bioinformaticians you will never work with just one sequence. You will use FASTA files with multiple sequences. Let’s see how base R handles those.</p>
<p><strong>Importing and working with FASTA files</strong></p>
<p>First, what are FASTA files?</p>
<p>FASTA files are text files in the <a href="https://en.wikipedia.org/wiki/FASTA_format">FASTA format</a>. The FASTA format requires that the first line of each sequence be a header, denoted by <code>&gt;</code> (greater than) followed by a description of the sequence, e.g., <code>&gt;E.coli strain K12 complete chromosome</code>. Next are all the letters denoting nucleotides or amino acids with no spaces (basically a string). Sequences in FASTA format are universally used by all sequence repositories, and FASTA files (generally .fa or .fasta extensions, though any txt file with the format will work) are universally used. Because FASTA files are essentially text files, it is easy to import them using the <code>file()</code> and <code>readLines()</code> functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Let's import </span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> nuc_fa <span class="ot">&lt;-</span> <span class="fu">readLines</span>(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">file</span>(</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="st">"https://raw.githubusercontent.com/idohatam/Biol-3315-files/main/practice_nuc.fa"</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="at">open =</span> <span class="st">"r"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in
readLines(file("https://raw.githubusercontent.com/idohatam/Biol-3315-files/main/practice_nuc.fa",
: incomplete final line found on
'https://raw.githubusercontent.com/idohatam/Biol-3315-files/main/practice_nuc.fa'</code></pre>
</div>
</div>
<p>Now, let’s inspect the file.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># In this file each sequence is contained in multiple lines</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># As can be seen in this example, lines 2-4 still belong to sequence 1 </span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> nuc_fa[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "&gt;k141_185580_GM_enrich_2.fa:145193-145801 "                                      
[2] "AACTTTGTTTATAAATAATATTTTATCTCCAATAGCATTTTTAAACAATCCATTTTCATTTAAAATTATTTGATATAATA"
[3] "TATCTAAATTTATGTACTTATCATTTATATTTTTAATATCTATCAAACACTTAAATTCTTTCAATCTATGTATATTTTTA"
[4] "TCACTGATTTCCATTTTATAAGTAGTTATATCTAATATTCCAATAGTCTTAGTAGTTTTATTATAGACTACTGGCTCATT"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Let's use a shortcut to do that, and see that the file contains 5 sequences</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> (<span class="fu">length</span>(hdr <span class="ot">&lt;-</span> <span class="fu">str_which</span>(nuc_fa, <span class="st">"&gt;"</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<p>Now that we know the beginning and the end line of each sequence, we can gather some stats. Let’s see how long each sequence is using an elegant for loop.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Note: no hard coding. This way, you can reuse this code even if the next file has more sequences.</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> seq_length <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(hdr))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># The for loop</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(hdr)) {</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="co"># What is the role of this if else statement?</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="cf">if</span>(i <span class="sc">&lt;</span> <span class="fu">length</span>(hdr)){</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     seq_length[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">nchar</span>(nuc_fa[(hdr[i]<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(hdr[i<span class="sc">+</span><span class="dv">1</span>]<span class="sc">-</span><span class="dv">1</span>)]))</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   } <span class="cf">else</span> { </span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       seq_length[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">nchar</span>(nuc_fa[(hdr[i]<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span><span class="fu">length</span>(nuc_fa)]))</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     }</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span> }</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Let's get the stats on sequence length</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">summary</span>(seq_length)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  544.0   551.0   609.0   655.2   786.0   786.0 </code></pre>
</div>
</div>
<p>We can see that the longest sequence is 786 nucleotides, and the shortest is 544 nucleotides.</p>
<p>What if there is a need to perform more tasks with the sequences? For example, find ORFs, compile the reverse and complementary sequences, or align the sequences against each other, build a phylogenetic tree, etc.?</p>
<p>The fact that the sequences are divided into lines (different elements of a character vector) makes it difficult to process them, and they need to be housed in a new container. Two possible ways to do it are:</p>
<ul>
<li><p>House them in a dataframe: column 1 will be the header, column 2 will be the concatenated line of each sequence, and column 3 will be the reverse complement sequence.</p></li>
<li><p>House each of them in a list: the name of each element will be the header, and a second list would be the reverse complement sequence. The two lists could be merged as two nested lists.</p></li>
</ul>
<p>Both options will require a fair bit of code. Let’s see what the dataframe option looks like.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Let's start with creating 3 vectors</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Sequence headers</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> hdrs <span class="ot">&lt;-</span> nuc_fa[hdr]</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># A vector to house the seqs</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sqs <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"H"</span>, <span class="fu">length</span>(hdr))</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Vector to house the reverse complement seqs</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sqs_rc <span class="ot">&lt;-</span> sqs</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now let’s write a for loop to merge all lines of each sequence to one sequence and also produce the reverse complementary sequence.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq_along</span>(hdr)){</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="cf">if</span>(i <span class="sc">&lt;</span> <span class="fu">length</span>(hdr)){</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     sqs[i] <span class="ot">&lt;-</span> <span class="fu">paste</span>(nuc_fa[(hdr[i]<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(hdr[i<span class="sc">+</span><span class="dv">1</span>]<span class="sc">-</span><span class="dv">1</span>)], <span class="at">collapse =</span> <span class="st">""</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="co"># My function also makes sure to check if the string is split or not and splits it if needed.</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     sqs_rc[i] <span class="ot">&lt;-</span> <span class="fu">rev_comp</span>(sqs[i])</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     </span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   } <span class="cf">else</span>{</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     </span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     sqs[i] <span class="ot">&lt;-</span> <span class="fu">paste</span>(nuc_fa[(hdr[i]<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span><span class="fu">length</span>(nuc_fa)], <span class="at">collapse =</span> <span class="st">""</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     </span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     sqs_rc[i] <span class="ot">&lt;-</span> <span class="fu">rev_comp</span>(sqs[i])</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     </span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   }</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span> }</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Now let's bind the vectors as dataframe</span></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> df_sqs <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(hdrs, sqs, sqs_rc, <span class="at">stringsAsFactors =</span> F)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now that the sequences are housed in a dataframe, it is easy to get what we need from them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Calculate</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> df_sqs <span class="ot">&lt;-</span> df_sqs <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Seq.len =</span> <span class="fu">nchar</span>(sqs))</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Get sequence stats</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">summary</span>(df_sqs<span class="sc">$</span>Seq.len)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  544.0   551.0   609.0   655.2   786.0   786.0 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Get all ATGs</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> ATGs <span class="ot">&lt;-</span> <span class="fu">str_locate_all</span>(df_sqs<span class="sc">$</span>sqs, <span class="st">"ATG"</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Result is a list with 5 elements, each with the positions of ATG of a particular sequence</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># This is for the first sequence</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> ATGs[[<span class="dv">1</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     start end
[1,]    92  94
[2,]   148 150
[3,]   317 319
[4,]   386 388
[5,]   467 469
[6,]   543 545</code></pre>
</div>
</div>
<p>Because dataframes require that all columns be of the same length, they are not very flexible and only allow you to work with strings. The second option, working with lists, affords more flexibility since each element of the list is independent of each other and can even be another list. Therefore, you could generate a set of nested lists where the outer list will house all other lists, and each nested list will contain the string and vectorized sequences.</p>
<p>Example:</p>
<p>List of all sequences (</p>
<p>List of sequence 1 (element one (string of sequence), element two (string of reverse complement), element 3 (character vector of sequence), element 4 (character vector of reverse complement)) . . . List of sequence 5 (….) )</p>
<p>From there you can add more elements such as location of all ORFs, corresponding RNA and amino acid sequences. However, as you can see, all these will require <strong>a lot of coding!</strong> Luckily you don’t have to reinvent the wheel since there are a few R packages designed to handle biological strings. This, however, was not a pointless exercise because you gained an understanding of some of the data structures generated by these packages, and hopefully it will make it easier for you to work with them. Furthermore, now you know what it takes to write a package like the ones you will use. This understanding will serve you when you will be required to develop your own packages when you work as a bioinformatician.</p>
<p><br></p>
</section>
<section id="biostrings" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="biostrings"><span class="header-section-number">5.3</span> <strong>Biostrings</strong></h2>
<p>The first package we’ll work with is <code>Biostrings</code>. As its name suggests, this is a package that handles biological strings. It can handle DNA, RNA, and amino acid sequences and is also capable of pattern matching, which helps with sequence look-up and alignment (albeit limited in that respect). <code>Biostrings</code> allows you to import individual sequences or FASTA files containing multiple sequences.</p>
<p>Biostrings uses a specialized container class called <code>XString</code> to store sequences. <code>XString</code> is similar to a character vector; however, unlike a vector, it can only house a single string.</p>
<p>The <code>XString</code> class has four subclasses:</p>
<ol type="1">
<li><p><code>DNAString</code> - stores DNA sequences</p></li>
<li><p><code>RNAString</code> - stores RNA sequences</p></li>
<li><p><code>AAString</code> - stores amino acid sequences</p></li>
<li><p><code>BString</code> - stores general strings</p></li>
</ol>
<p>Let’s look at a few examples of working with strings using <code>Biostrings</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># As always, let's generate a random string and convert it to an XString object</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> string <span class="ot">&lt;-</span> <span class="st">"This is a random string (is it random though?!)"</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Now let's call it as DNAString</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> string <span class="ot">&lt;-</span> <span class="fu">DNAString</span>(string)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-error">
<pre><code>Error in `.Call2()`:
! key 105 (char 'i') not in lookup table</code></pre>
</div>
</div>
<p>Uh-oh, an error message. This is because <code>DNAString</code> is limited in which characters it accepts. Remember, only <code>BString</code> is character-agnostic.</p>
<p>Let’s see which characters <code>DNAString</code> accepts.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> DNA_ALPHABET</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "A" "C" "G" "T" "M" "R" "W" "S" "Y" "K" "V" "H" "D" "B" "N" "-" "+" "."</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># In case you were wondering what each of those letters mean, Biostrings has a function with the </span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># details. Useful when designing synthetic sequences like primers</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> IUPAC_CODE_MAP</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     A      C      G      T      M      R      W      S      Y      K      V 
   "A"    "C"    "G"    "T"   "AC"   "AG"   "AT"   "CG"   "CT"   "GT"  "ACG" 
     H      D      B      N 
 "ACT"  "AGT"  "CGT" "ACGT" </code></pre>
</div>
</div>
<p>As you can see, <code>DNAString</code> accepts more than just ATCG. It also accepts base categories, strand orientation (+/-), and alignment gaps.</p>
<p>Let’s see which characters the other two restricted subclasses accept.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> RNA_ALPHABET</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "A" "C" "G" "U" "M" "R" "W" "S" "Y" "K" "V" "H" "D" "B" "N" "-" "+" "."</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> AA_ALPHABET</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "A" "R" "N" "D" "C" "Q" "E" "G" "H" "I" "L" "K" "M" "F" "P" "S" "T" "W" "Y"
[20] "V" "U" "O" "B" "J" "Z" "X" "*" "-" "+" "."</code></pre>
</div>
</div>
<p>Now, let’s use the acceptable alphabet to generate a string that will not produce an error.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># I am creating an AA sequence, using AA_STANDARD to just include the standard amino acid symbols</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Note that I am setting seed. If you want to reproduce the same random string I produced, </span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># you should set seed to the same number</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> </span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> casein <span class="ot">&lt;-</span> <span class="fu">AAString</span>(<span class="fu">paste</span>(<span class="fu">sample</span>(AA_STANDARD, <span class="dv">10</span>, <span class="at">replace =</span> T), <span class="at">collapse =</span> <span class="st">""</span>))</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> casein</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>10-letter AAString object
seq: PYFNIWLCVF</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">class</span>(casein)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "AAString"
attr(,"package")
[1] "Biostrings"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Note, typeof will output S4. This is a different object type than ones we have worked with so far</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">typeof</span>(casein)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "S4"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">str</span>(casein)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Formal class 'AAString' [package "Biostrings"] with 5 slots
  ..@ shared         :Formal class 'SharedRaw' [package "XVector"] with 2 slots
  .. .. ..@ xp                    :&lt;externalptr&gt; 
  .. .. ..@ .link_to_cached_object:&lt;environment: 0x12fc68228&gt; 
  ..@ offset         : int 0
  ..@ length         : int 10
  ..@ elementMetadata: NULL
  ..@ metadata       : list()</code></pre>
</div>
</div>
<p>One advantage of the <code>XString</code> class is that it allows you to treat the sequence both as a vector and as a string, making it easy to index, subset, and modify.</p>
<p>The code snippet below demonstrates how to access and modify an <code>XString</code> class object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Let's get the first element of the AA sequence</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> casein[<span class="dv">1</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1-letter AAString object
seq: P</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Let's subset</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> casein[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>5-letter AAString object
seq: PYFNI</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Another great feature of the XString class is that the string is mutable in the same way a vector </span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># is. Let's change the first AA to methionine.</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> </span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> casein[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">"M"</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Appending characters is done in the same way you would a character vector.</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> casein[<span class="dv">11</span>] <span class="ot">&lt;-</span> <span class="st">"J"</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Reminder that gaps can also be added.</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> casein[<span class="dv">10</span>] <span class="ot">&lt;-</span> <span class="st">"-"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Because XString class objects are treated as strings, it is easy to use functions from base R to process them. Let’s use <code>grepl()</code>, which works like <code>str_detect</code> for pattern matching. Note that I am calling <code>base::</code> because <code>grepl</code> is masked by <code>BiocGenerics</code>, a Bioconductor package. It will work the same if you choose to use the <code>BiocGenerics</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> base<span class="sc">::</span><span class="fu">grepl</span>(<span class="st">"MYFNI"</span>, casein)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p><code>tidyverse</code> packages are more particular about the data types they accept and require some manipulation. I used the base R function <code>toString()</code> to turn casein into… a string.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">str_detect</span>(<span class="fu">toString</span>(casein), <span class="st">"MYFNI"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>It is also possible to use base R functions like <code>gsub()</code> and <code>stringr</code> functions like <code>str_replace()</code> to edit casein; however, it takes a bit of tinkering to keep it as an XString element. Still, it is worthwhile if editing chunks of sequence. Note that here I am also introducing you to base R’s native pipe operator <code>|&gt;</code>. We won’t use it often, but it’s worth knowing.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># tidyverse</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> casein2 <span class="ot">&lt;-</span> casein <span class="sc">%&gt;%</span> toString <span class="sc">%&gt;%</span> <span class="fu">str_replace</span>(<span class="st">"MYFNI"</span>, <span class="st">"MYXGT"</span>) <span class="sc">%&gt;%</span> <span class="fu">AAString</span>()</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># base R with the native pipe</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> casein3 <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"MYFNI"</span>, <span class="st">"MYXGT"</span>, casein) <span class="sc">|&gt;</span> <span class="fu">AAString</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The Biostrings package has some useful functions with respect to sequence processing. Let’s look at some of them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Biostrings can sum up the frequency of each letter (i.e., AA in this case)</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> x <span class="ot">&lt;-</span> <span class="fu">alphabetFrequency</span>(casein)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Output is a named vector, not the most convenient way to present results.</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> x</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>A R N D C Q E G H I L K M F P S T W Y V U O B J Z X * - + . 
0 0 1 0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Can subset to only include those larger than 0 (and normalize to percent)</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># as.prob gives the probability of each AA</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> x <span class="ot">&lt;-</span> <span class="fu">alphabetFrequency</span>(casein, <span class="at">as.prob =</span> T)[<span class="fu">alphabetFrequency</span>(casein) <span class="sc">&gt;</span> <span class="dv">0</span>] <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> x</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       N        C        I        L        M        F        W        Y 
9.090909 9.090909 9.090909 9.090909 9.090909 9.090909 9.090909 9.090909 
       V        J        - 
9.090909 9.090909 9.090909 </code></pre>
</div>
</div>
<p>Let’s do the same to a longer sequence, this time DNA. First, convert the <code>sq1</code> string to <code>XString</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># First, convert the sq1 string to XString</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq1.bio <span class="ot">&lt;-</span> <span class="fu">DNAString</span>(sq1)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># If using nucleotides, can use the argument baseOnly to only get ATCG</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> x.d <span class="ot">&lt;-</span> <span class="fu">alphabetFrequency</span>(sq1.bio, <span class="at">baseOnly =</span> T, <span class="at">as.prob =</span> T) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> x.d</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    A     C     G     T other 
   24    29    30    17     0 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Alternatively, it's possible to look at the proportion of only one base with letterFrequency</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">letterFrequency</span>(sq1.bio, <span class="st">"C"</span>, <span class="at">as.prob =</span> T) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> C 
29 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">letterFrequency</span>(sq1.bio, <span class="fu">c</span>(<span class="st">"G"</span>, <span class="st">"C"</span>), <span class="at">as.prob =</span> T) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> G  C 
30 29 </code></pre>
</div>
</div>
<p>Now let’s convert the frequency information of all nucleotides to a dataframe and plot it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> x.d.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">names</span>(x.d), x.d, <span class="at">stringsAsFactors =</span> F)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">ggplot</span>(x.d.df, <span class="fu">aes</span>(<span class="at">y =</span> x.d, <span class="at">x =</span> names.x.d.)) <span class="sc">+</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">16</span>) <span class="sc">+</span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">xlab</span>(<span class="st">"Bases"</span>) <span class="sc">+</span></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">ylab</span>(<span class="st">"Frequency"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-lab3_biological_data1_files/figure-html/biostrings frequency plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Biostrings allows you to reverse, complement, and even translate nucleotide sequences.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Reverse a sequence</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq1.bio.rev <span class="ot">&lt;-</span> Biostrings<span class="sc">::</span><span class="fu">reverse</span>(sq1.bio)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Complement a sequence</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq1.bio.comp <span class="ot">&lt;-</span> <span class="fu">complement</span>(sq1.bio)</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Reverse complement a sequence</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq1.bio.rev.comp <span class="ot">&lt;-</span> <span class="fu">reverseComplement</span>(sq1.bio)</span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq1.bio</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>100-letter DNAString object
seq: GAAGATGTCTCGTCTCCACCTGGGGGGTAGGGTCCC...CCGGAGCGGGGAACCATATCGAACCAGTATAGAAAT</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> sq1.bio.rev</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>100-letter DNAString object
seq: TAAAGATATGACCAAGCTATACCAAGGGGCGAGGCC...CCCTGGGATGGGGGGTCCACCTCTGCTCTGTAGAAG</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> sq1.bio.comp</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>100-letter DNAString object
seq: CTTCTACAGAGCAGAGGTGGACCCCCCATCCCAGGG...GGCCTCGCCCCTTGGTATAGCTTGGTCATATCTTTA</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> sq1.bio.rev.comp</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>100-letter DNAString object
seq: ATTTCTATACTGGTTCGATATGGTTCCCCGCTCCGG...GGGACCCTACCCCCCAGGTGGAGACGAGACATCTTC</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Translate a sequence</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq1.bio.t <span class="ot">&lt;-</span> <span class="fu">translate</span>(sq1.bio)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in .Call2("DNAStringSet_translate", x, skip_code,
dna_codes[codon_alphabet], : last base was ignored</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> sq1.bio.t</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>33-letter AAString object
seq: EDVSSPPGG*GPSDVHHPWAHAGAGNHIEPV*K</code></pre>
</div>
</div>
<hr>
<p><strong>Quick R exercise</strong> Use <code>?Biostrings::translate</code> to see what arguments the function takes. Can it be used to predict ORFs?</p>
<hr>
<p><strong>Working with multiple sequences</strong></p>
<p>As you know by now, bioinformaticians do not work with a single sequence but rather with many sequences in parallel. <code>Biostrings</code> offers the class <code>XStringSet</code> as a container for multiple sequences. Here too, it is a combination of a list and a vector. Think of it as a list of XString class objects.</p>
<p>Just like with the <code>XString</code>, the <code>XStringSet</code> offers four subclasses:</p>
<ol type="1">
<li><p><code>DNAStringSet</code> to house DNA sequences</p></li>
<li><p><code>RNAStringSet</code> to house RNA sequences</p></li>
<li><p><code>AAStringSet</code> to house amino acid sequences</p></li>
<li><p><code>BStringSet</code> to house sets of diverse strings</p></li>
</ol>
<p>This means that a <code>BStringSet</code> can house the DNA, RNA, and AA sequences of a particular gene.</p>
<p>Let’s see what it looks like.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Let's generate a DNAStringSet</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq1.set <span class="ot">&lt;-</span> <span class="fu">DNAStringSet</span>(<span class="fu">c</span>(<span class="fu">paste</span>(sq1.bio), <span class="fu">paste</span>(sq1.bio.rev),</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>                           <span class="fu">paste</span>(sq1.bio.comp), <span class="fu">paste</span>(sq1.bio.rev.comp)))</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># As you can see, an XStringSet object shows a glimpse of the sequence and the length of each </span></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># sequence</span></span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq1.set</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>DNAStringSet object of length 4:
    width seq
[1]   100 GAAGATGTCTCGTCTCCACCTGGGGGGTAGGGTC...GAGCGGGGAACCATATCGAACCAGTATAGAAAT
[2]   100 TAAAGATATGACCAAGCTATACCAAGGGGCGAGG...TGGGATGGGGGGTCCACCTCTGCTCTGTAGAAG
[3]   100 CTTCTACAGAGCAGAGGTGGACCCCCCATCCCAG...CTCGCCCCTTGGTATAGCTTGGTCATATCTTTA
[4]   100 ATTTCTATACTGGTTCGATATGGTTCCCCGCTCC...ACCCTACCCCCCAGGTGGAGACGAGACATCTTC</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Sequences housed in an XStringSet object can have names. Let's name our sequences</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">names</span>(sq1.set) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"sq1.bio"</span>, <span class="st">"sq1.bio.rev"</span>, <span class="st">"sq1.bio.comp"</span>, <span class="st">"sq1.bio.rev.comp"</span>)</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> sq1.set</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>DNAStringSet object of length 4:
    width seq                                               names               
[1]   100 GAAGATGTCTCGTCTCCACCTGG...CCATATCGAACCAGTATAGAAAT sq1.bio
[2]   100 TAAAGATATGACCAAGCTATACC...GGTCCACCTCTGCTCTGTAGAAG sq1.bio.rev
[3]   100 CTTCTACAGAGCAGAGGTGGACC...GGTATAGCTTGGTCATATCTTTA sq1.bio.comp
[4]   100 ATTTCTATACTGGTTCGATATGG...CCAGGTGGAGACGAGACATCTTC sq1.bio.rev.comp</code></pre>
</div>
</div>
<p>By now you probably realized that the <code>XStringSet</code> can house sequences from FASTA files. Let’s import the FASTA file practice_nuc.fa as an <code>XStringSet</code> object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Using the readDNAStringSet function to import the FASTA file.</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Note that if the FASTA file would have contained both AA and nucleotides, you could have imported </span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># it using the readBStringSet function</span></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set <span class="ot">&lt;-</span> <span class="fu">readDNAStringSet</span>(<span class="st">"https://raw.githubusercontent.com/idohatam/Biol-3315-files/main/practice_nuc.fa"</span>)</span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># As you can see, the imported file is organized very conveniently</span></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>DNAStringSet object of length 5:
    width seq                                               names               
[1]   609 AACTTTGTTTATAAATAATATTT...TTTATATTGAAAATTTTCGCTAT k141_185580_GM_en...
[2]   544 CTAATTCACAAATCTGCGCGCGA...TGGGGGATGTAAGAGACGCATGA k141_37775_GM_EP_...
[3]   786 CTATCTCACCAGTCTGCGCGTGA...ATTATTTCCATCAGACTCCATGG k141_45685_Lagoon...
[4]   786 CTATCTCACCAGTCTGCGCGTGA...ATTATTTCCATCAGACTCCATGG k141_51585_GM_EP_...
[5]   551 GAAGTAATAGCAATAGCAGGTAC...AAAGCCTCCGGCGAAAGGATCCT k141_5273_LagoonA...</code></pre>
</div>
</div>
<p>Objects of class <code>XStringSet</code> can be subset, indexed, and modified similar to objects of class <code>XString</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># How many elements are in the XStringSet?</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">length</span>(fa.set)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># What is the length of each of the sequences?</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">width</span>(fa.set)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 609 544 786 786 551</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Subset the first element</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Note that when subsetting an XStringSet, the output is an XStringSet and not an XString</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set[<span class="dv">1</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>DNAStringSet object of length 1:
    width seq                                               names               
[1]   609 AACTTTGTTTATAAATAATATTT...TTTATATTGAAAATTTTCGCTAT k141_185580_GM_en...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Because XStringSet objects are named, they can be indexed and subset using the $ operator.</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># In this case the output is an XString object and it can be treated as such</span></span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set<span class="sc">$</span><span class="st">`</span><span class="at">k141_185580_GM_enrich_2.fa:145193-145801 </span><span class="st">`</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>609-letter DNAString object
seq: AACTTTGTTTATAAATAATATTTTATCTCCAATAGC...AATATCTTTATTTTTTATATTGAAAATTTTCGCTAT</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># First character of the XString</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set<span class="sc">$</span><span class="st">`</span><span class="at">k141_185580_GM_enrich_2.fa:145193-145801 </span><span class="st">`</span>[<span class="dv">1</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1-letter DNAString object
seq: A</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Can be modified like a regular vector</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set<span class="sc">$</span><span class="st">`</span><span class="at">k141_185580_GM_enrich_2.fa:145193-145801 </span><span class="st">`</span>[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">"G"</span></span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set<span class="sc">$</span><span class="st">`</span><span class="at">k141_185580_GM_enrich_2.fa:145193-145801 </span><span class="st">`</span>[<span class="dv">1</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1-letter DNAString object
seq: G</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Because XStringSet objects behave like a list, strings can be accessed using "[[ ]]"</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set[[<span class="dv">1</span>]][<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">"A"</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set[[<span class="dv">1</span>]][<span class="dv">1</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1-letter DNAString object
seq: A</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># It is easy to access a range of sequences</span></span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>DNAStringSet object of length 3:
    width seq                                               names               
[1]   609 AACTTTGTTTATAAATAATATTT...TTTATATTGAAAATTTTCGCTAT k141_185580_GM_en...
[2]   544 CTAATTCACAAATCTGCGCGCGA...TGGGGGATGTAAGAGACGCATGA k141_37775_GM_EP_...
[3]   786 CTATCTCACCAGTCTGCGCGTGA...ATTATTTCCATCAGACTCCATGG k141_45685_Lagoon...</code></pre>
</div>
</div>
<p>One of the advantages of an <code>XStringSet</code> is the ability to manipulate multiple sequences at the same time.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># alphabetFrequency can calculate base frequency for every sequence. Output is a matrix. Let's </span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># output as dataframe</span></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set.frq <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">alphabetFrequency</span>(fa.set, <span class="at">baseOnly =</span> T, <span class="at">as.prob =</span> T) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Let's organize it a bit, add the names and plot</span></span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set.frq <span class="ot">&lt;-</span> fa.set.frq <span class="sc">%&gt;%</span>  <span class="fu">mutate</span>(<span class="at">Sqs =</span> <span class="fu">names</span>(fa.set)) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Sqs, <span class="fu">everything</span>(), <span class="sc">-</span>other) <span class="sc">%&gt;%</span></span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">gather</span>(<span class="at">key =</span> <span class="st">"Bases"</span>, <span class="at">value =</span> <span class="st">"Frequency"</span>, <span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>)</span>
<span id="cb116-8"><a href="#cb116-8" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb116-9"><a href="#cb116-9" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Not the prettiest, but you can see that the one at the top left has a much lower GC content than </span></span>
<span id="cb116-10"><a href="#cb116-10" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># the rest</span></span>
<span id="cb116-11"><a href="#cb116-11" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">ggplot</span>(fa.set.frq, <span class="fu">aes</span>(<span class="at">x =</span> Bases, <span class="at">y =</span> Frequency)) <span class="sc">+</span></span>
<span id="cb116-12"><a href="#cb116-12" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb116-13"><a href="#cb116-13" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">facet_wrap</span>(<span class="sc">~</span>Sqs) <span class="sc">+</span></span>
<span id="cb116-14"><a href="#cb116-14" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-lab3_biological_data1_files/figure-html/XStringSet working-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Similarly, sequences can be reversed, complemented, reverse complemented, and translated in bulk.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Reverse complement</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set.rc <span class="ot">&lt;-</span> <span class="fu">reverseComplement</span>(fa.set)</span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb117-4"><a href="#cb117-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.set</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>DNAStringSet object of length 5:
    width seq                                               names               
[1]   609 AACTTTGTTTATAAATAATATTT...TTTATATTGAAAATTTTCGCTAT k141_185580_GM_en...
[2]   544 CTAATTCACAAATCTGCGCGCGA...TGGGGGATGTAAGAGACGCATGA k141_37775_GM_EP_...
[3]   786 CTATCTCACCAGTCTGCGCGTGA...ATTATTTCCATCAGACTCCATGG k141_45685_Lagoon...
[4]   786 CTATCTCACCAGTCTGCGCGTGA...ATTATTTCCATCAGACTCCATGG k141_51585_GM_EP_...
[5]   551 GAAGTAATAGCAATAGCAGGTAC...AAAGCCTCCGGCGAAAGGATCCT k141_5273_LagoonA...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> fa.set.rc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>DNAStringSet object of length 5:
    width seq                                               names               
[1]   609 ATAGCGAAAATTTTCAATATAAA...AAATATTATTTATAAACAAAGTT k141_185580_GM_en...
[2]   544 TCATGCGTCTCTTACATCCCCCA...TCGCGCGCAGATTTGTGAATTAG k141_37775_GM_EP_...
[3]   786 CCATGGAGTCTGATGGAAATAAT...TCACGCGCAGACTGGTGAGATAG k141_45685_Lagoon...
[4]   786 CCATGGAGTCTGATGGAAATAAT...TCACGCGCAGACTGGTGAGATAG k141_51585_GM_EP_...
[5]   551 AGGATCCTTTCGCCGGAGGCTTT...GTACCTGCTATTGCTATTACTTC k141_5273_LagoonA...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Pattern matching can also be done for all the sequences. Let's search for start codons</span></span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">str_locate_all</span>(<span class="fu">toString</span>(fa.set), <span class="st">"ATG"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
      start  end
 [1,]    92   94
 [2,]   148  150
 [3,]   317  319
 [4,]   386  388
 [5,]   467  469
 [6,]   543  545
 [7,]   642  644
 [8,]   748  750
 [9,]   788  790
[10,]   885  887
[11,]   921  923
[12,]   964  966
[13,]  1024 1026
[14,]  1127 1129
[15,]  1132 1134
[16,]  1139 1141
[17,]  1152 1154
[18,]  1252 1254
[19,]  1272 1274
[20,]  1341 1343
[21,]  1425 1427
[22,]  1504 1506
[23,]  1515 1517
[24,]  1755 1757
[25,]  1940 1942
[26,]  2040 2042
[27,]  2060 2062
[28,]  2129 2131
[29,]  2213 2215
[30,]  2292 2294
[31,]  2303 2305
[32,]  2543 2545
[33,]  2728 2730
[34,]  2776 2778
[35,]  2864 2866
[36,]  2884 2886
[37,]  2890 2892
[38,]  2903 2905
[39,]  2981 2983
[40,]  3014 3016
[41,]  3046 3048
[42,]  3063 3065
[43,]  3139 3141
[44,]  3149 3151
[45,]  3214 3216</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="seqinr" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="seqinr"><span class="header-section-number">5.4</span> <strong>seqinr</strong></h2>
<p>An alternative package to <code>Biostrings</code> is <code>seqinr</code>. It is not a Bioconductor package and thus uses standard R objects. Much less elegant than <code>Biostrings</code>, yet it has some perks that are worth getting to know.</p>
<p>First, let’s see how <code>seqinr</code> handles sequences by importing the practice_nuc FASTA file.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Import the file</span></span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.snr <span class="ot">&lt;-</span> <span class="fu">read.fasta</span>(<span class="at">file =</span> <span class="st">"https://raw.githubusercontent.com/idohatam/Biol-3315-files/main/practice_nuc.fa"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in readLines(file): incomplete final line found on
'https://raw.githubusercontent.com/idohatam/Biol-3315-files/main/practice_nuc.fa'</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Note that this is a list</span></span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">str</span>(fa.snr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 5
 $ k141_185580_GM_enrich_2.fa:145193-145801       : 'SeqFastadna' chr [1:609] "a" "a" "c" "t" ...
  ..- attr(*, "name")= chr "k141_185580_GM_enrich_2.fa:145193-145801"
  ..- attr(*, "Annot")= chr "&gt;k141_185580_GM_enrich_2.fa:145193-145801 "
 $ k141_37775_GM_EP_bin_8.fa:2212-2755            : 'SeqFastadna' chr [1:544] "c" "t" "a" "a" ...
  ..- attr(*, "name")= chr "k141_37775_GM_EP_bin_8.fa:2212-2755"
  ..- attr(*, "Annot")= chr "&gt;k141_37775_GM_EP_bin_8.fa:2212-2755 "
 $ k141_45685_LagoonA_Enrichbin_4.fa:121791-122576: 'SeqFastadna' chr [1:786] "c" "t" "a" "t" ...
  ..- attr(*, "name")= chr "k141_45685_LagoonA_Enrichbin_4.fa:121791-122576"
  ..- attr(*, "Annot")= chr "&gt;k141_45685_LagoonA_Enrichbin_4.fa:121791-122576 "
 $ k141_51585_GM_EP_bin_1.fa:55098-55883          : 'SeqFastadna' chr [1:786] "c" "t" "a" "t" ...
  ..- attr(*, "name")= chr "k141_51585_GM_EP_bin_1.fa:55098-55883"
  ..- attr(*, "Annot")= chr "&gt;k141_51585_GM_EP_bin_1.fa:55098-55883 "
 $ k141_5273_LagoonA_EP_bin_5.fa:13519-14069      : 'SeqFastadna' chr [1:551] "g" "a" "a" "g" ...
  ..- attr(*, "name")= chr "k141_5273_LagoonA_EP_bin_5.fa:13519-14069"
  ..- attr(*, "Annot")= chr "&gt;k141_5273_LagoonA_EP_bin_5.fa:13519-14069 "</code></pre>
</div>
</div>
<p>As can be seen, the output from <code>read.fasta()</code> is a list. Each sequence is an element of the list stored as a character vector, resembling the exercise we did at the beginning of the class. Another thing to note is that the characters are not capitalized. This means that when pattern matching is required, the vectors need to be converted to strings. <code>seqinr</code> has two functions: <code>c2s()</code> and <code>s2c()</code>, which convert characters to strings and vice versa, respectively.</p>
<p>Let’s look at an example for pattern matching with <code>seqinr</code> by identifying all start codons in all the sequences in the file.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Since fa.snr is a list, lapply is used to run c2s on all elements of the list</span></span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Remember that the apply family of functions is basically an optimized for loop</span></span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># lapply takes a list and runs a function on all its elements and outputs a list with the results</span></span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Then str_locate_all is used to find all ATG. (?i) is for case insensitivity</span></span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">str_locate_all</span>(<span class="fu">lapply</span>(fa.snr, c2s), <span class="st">"(?i)ATG"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`k141_185580_GM_enrich_2.fa:145193-145801`
     start end
[1,]    92  94
[2,]   148 150
[3,]   317 319
[4,]   386 388
[5,]   467 469
[6,]   543 545

$`k141_37775_GM_EP_bin_8.fa:2212-2755`
      start end
 [1,]    31  33
 [2,]   137 139
 [3,]   177 179
 [4,]   274 276
 [5,]   310 312
 [6,]   353 355
 [7,]   413 415
 [8,]   516 518
 [9,]   521 523
[10,]   528 530
[11,]   541 543

$`k141_45685_LagoonA_Enrichbin_4.fa:121791-122576`
     start end
[1,]    95  97
[2,]   115 117
[3,]   184 186
[4,]   268 270
[5,]   347 349
[6,]   358 360
[7,]   598 600
[8,]   783 785

$`k141_51585_GM_EP_bin_1.fa:55098-55883`
     start end
[1,]    95  97
[2,]   115 117
[3,]   184 186
[4,]   268 270
[5,]   347 349
[6,]   358 360
[7,]   598 600
[8,]   783 785

$`k141_5273_LagoonA_EP_bin_5.fa:13519-14069`
      start end
 [1,]    43  45
 [2,]   131 133
 [3,]   151 153
 [4,]   157 159
 [5,]   170 172
 [6,]   248 250
 [7,]   281 283
 [8,]   313 315
 [9,]   330 332
[10,]   406 408
[11,]   416 418
[12,]   481 483</code></pre>
</div>
</div>
<p>Apart from concatenating vectors and splitting strings, <code>seqinr</code> has some summary functions as well.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># count is a seqinr function that counts the occurrence of bases or a combination of bases</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># wordsize is the argument that controls combinations. When set to 1 it counts the occurrence of</span></span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># each nucleotide. If it was set to 3 it would count the occurrence of each codon.</span></span>
<span id="cb129-4"><a href="#cb129-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Note that within lapply I am specifying which package to use count from. </span></span>
<span id="cb129-5"><a href="#cb129-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># This is because we loaded multiple packages with a function named count and I want to make sure </span></span>
<span id="cb129-6"><a href="#cb129-6" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># lapply uses the correct one</span></span>
<span id="cb129-7"><a href="#cb129-7" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> </span>
<span id="cb129-8"><a href="#cb129-8" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">lapply</span>(fa.snr, seqinr<span class="sc">::</span>count, <span class="at">wordsize =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`k141_185580_GM_enrich_2.fa:145193-145801`

  a   c   g   t 
197  88  44 280 

$`k141_37775_GM_EP_bin_8.fa:2212-2755`

  a   c   g   t 
131 143 130 140 

$`k141_45685_LagoonA_Enrichbin_4.fa:121791-122576`

  a   c   g   t 
184 236 208 158 

$`k141_51585_GM_EP_bin_1.fa:55098-55883`

  a   c   g   t 
184 236 208 158 

$`k141_5273_LagoonA_EP_bin_5.fa:13519-14069`

  a   c   g   t 
157 122 144 128 </code></pre>
</div>
</div>
<p>The function <code>GC</code> from <code>seqinr</code> calculates %GC. Just as <code>count</code>, it does not access a list, and you have to present it with a vector, so I used <code>lapply</code> to iterate over each of the sequences.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">lapply</span>(fa.snr, GC)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`k141_185580_GM_enrich_2.fa:145193-145801`
[1] 0.2167488

$`k141_37775_GM_EP_bin_8.fa:2212-2755`
[1] 0.5018382

$`k141_45685_LagoonA_Enrichbin_4.fa:121791-122576`
[1] 0.5648855

$`k141_51585_GM_EP_bin_1.fa:55098-55883`
[1] 0.5648855

$`k141_5273_LagoonA_EP_bin_5.fa:13519-14069`
[1] 0.4827586</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Let's get it into a plottable dataframe</span></span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Note how I chain lapplys here. These are the equivalent of a nested for loop</span></span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> fa.snr.gc <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">lapply</span>(<span class="fu">lapply</span>(fa.snr, GC), cbind)) <span class="sc">%&gt;%</span></span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">gather</span>(<span class="at">key =</span> <span class="st">"Sqs"</span>, <span class="at">value =</span> <span class="st">"GC"</span>) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">GC =</span> GC <span class="sc">*</span> <span class="dv">100</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
<p><strong>Quick R exercise</strong></p>
<p>Use <code>ggplot2</code> to plot a bar graph of the GC content we just calculated.</p>
<hr>
<p>While <code>seqinr</code> does not seem impressive compared to <code>Biostrings</code>, it does have some perks. One of them is the ability to download sequences straight from releases of online databases such as GenBank and EMBL stored on servers of the University of Lyon in France. It’s worth noting that it is not the only package that can do that. <code>ape</code> is another package that can do that, and you will be introduced to it in lab #4.</p>
<p>First, let’s inspect which sequence repositories <code>seqinr</code> can interface with.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Getting the list of repositories</span></span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Note, to prevent masking, the code specifies to use choosebank from the seqinr package</span></span>
<span id="cb134-3"><a href="#cb134-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> </span>
<span id="cb134-4"><a href="#cb134-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> repos <span class="ot">&lt;-</span> seqinr<span class="sc">::</span><span class="fu">choosebank</span>()</span>
<span id="cb134-5"><a href="#cb134-5" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Large list </span></span>
<span id="cb134-6"><a href="#cb134-6" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> repos</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In order to download sequences from a database, you must first select it using the <code>choosebank()</code> function. Here we will work with <code>genbank</code>, a comprehensive publicly available database of genetic sequences maintained by the NIH.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Chooses genbank</span></span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> bank <span class="ot">&lt;-</span> seqinr<span class="sc">::</span><span class="fu">choosebank</span>(<span class="at">bank =</span> <span class="st">"genbank"</span>, <span class="at">infobank =</span> T)</span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb135-4"><a href="#cb135-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Let's inspect the database</span></span>
<span id="cb135-5"><a href="#cb135-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> bank</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>As you can see, unfortunately the university works with a release that isn’t very up-to-date. Next, let’s download some sequences. Since <code>genbank</code> is a massive repository with tens, if not hundreds, of GB of data, let’s be targeted and download only sequences associated with the bacterium <em>Escherichia coli</em>.</p>
<p>To download the sequences, we will use the <code>query</code> function. The <code>listname</code> argument names your list, and the <code>query</code> argument tells the function which sequences to download. FYI 1: the <code>query</code> argument accepts regular expressions, which can simplify things. FYI 2: having an argument with an identical name to the function is not great practice.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> ecoliq <span class="ot">&lt;-</span> seqinr<span class="sc">::</span><span class="fu">query</span>(<span class="at">listname =</span> <span class="st">"ecoli"</span>, <span class="at">query =</span> <span class="st">"sp=Escherichia coli"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now let’s see how many sequences associated with <em>E. coli</em> are in our database, and download the first 10 with the function <code>getSequence</code>. Note the <code>query</code> outputs the sequences as a list. That’s why we need to use the function <code>unlist</code> to get a character vector.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># See how many seqs</span></span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">length</span>(ecoliq<span class="sc">$</span>req)</span>
<span id="cb137-3"><a href="#cb137-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb137-4"><a href="#cb137-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> ecoli10 <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">getSequence</span>(ecoliq<span class="sc">$</span>req[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="at">as.string =</span> <span class="cn">TRUE</span>))</span>
<span id="cb137-5"><a href="#cb137-5" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb137-6"><a href="#cb137-6" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Can treat individual elements as strings</span></span>
<span id="cb137-7"><a href="#cb137-7" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Get the first 10 characters of the first sequence.</span></span>
<span id="cb137-8"><a href="#cb137-8" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">substring</span>(ecoli10[<span class="dv">1</span>], <span class="dv">1</span>, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>As you can see, downloading sequences using seqinr stores the information in very basic containers. The next step will be to convert them to an <code>XStringSet</code> object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># DNAStringSet accepts vectors with strings as elements. That's why we used unlist in the previous </span></span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># step</span></span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> ecoli10dss <span class="ot">&lt;-</span> <span class="fu">DNAStringSet</span>(ecoli10)</span>
<span id="cb138-4"><a href="#cb138-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb138-5"><a href="#cb138-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Let's add the sequences' names to the XStringSet object.</span></span>
<span id="cb138-6"><a href="#cb138-6" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># This is a nifty trick using lapply in lieu of a for loop.</span></span>
<span id="cb138-7"><a href="#cb138-7" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># The [[ part tells lapply to use square brackets to subset each element of the list, and the 1 </span></span>
<span id="cb138-8"><a href="#cb138-8" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># tells it what position.</span></span>
<span id="cb138-9"><a href="#cb138-9" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Unlist turns the subset list into a vector that can then be used for the names function </span></span>
<span id="cb138-10"><a href="#cb138-10" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> </span>
<span id="cb138-11"><a href="#cb138-11" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">names</span>(ecoli10dss) <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">lapply</span>(ecoliq<span class="sc">$</span>req[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="st">'[['</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>From here it’s possible to calculate all the sequence stats you were introduced to at the beginning of the lab.</p>
<p><br></p>
</section>
<section id="exporting-sequence-elements" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="exporting-sequence-elements"><span class="header-section-number">5.5</span> <strong>Exporting sequence elements</strong></h2>
<p>Now that we got all of these sequences into R, how do we get them out? As always, there are several options.</p>
<p>Let’s start with the easiest option: writing a file using Biostrings.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># writeXStringSet exports XStringSets as FASTA files </span></span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># When you open the file you will notice that the name of each sequence is now the header </span></span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">writeXStringSet</span>(ecoli10dss, <span class="st">"ecoli1.fa"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>seqinr also allows you to export objects as FASTA files.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># write.fasta is a seqinr function to save objects as FASTA files</span></span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">write.fasta</span>(<span class="at">sequences =</span> fa.snr, <span class="at">names =</span> <span class="fu">names</span>(fa.snr), <span class="at">file.out =</span> <span class="st">"practice2.fa"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Lastly, base R write function allows you to also write FASTA files (since they are basically text files). Not as elegant since it requires a loop, which really slows down the operation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> i <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(ecoli10dss)) {</span>
<span id="cb141-4"><a href="#cb141-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="co"># This part writes the header</span></span>
<span id="cb141-5"><a href="#cb141-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">write</span>(<span class="fu">paste</span>(<span class="st">"&gt;"</span>, <span class="fu">names</span>(ecoli10dss[i]), <span class="at">sep =</span> <span class="st">""</span>), <span class="at">file =</span> <span class="st">"ecoli2.fa"</span>, <span class="at">append =</span> T)</span>
<span id="cb141-6"><a href="#cb141-6" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="co"># This part writes the sequence</span></span>
<span id="cb141-7"><a href="#cb141-7" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">write</span>(<span class="fu">paste0</span>(ecoli10dss[i]), <span class="at">file =</span> <span class="st">"ecoli2.fa"</span>, <span class="at">append =</span> T)</span>
<span id="cb141-8"><a href="#cb141-8" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span> }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>What do we do with the files now that we have them saved? You’ll see in the upcoming labs.</p>
</section>
</section>
<section id="summary-exercise" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> <strong>Summary exercise:</strong></h1>
<p>Start a script file in RStudio. Name it 3315_lab3_yourinitials.R. You will submit this script and output file (if applicable) to Brightspace.</p>
<p><strong>1.</strong> Write a function that reads FASTA files and counts how many sequences are present in the files and how long each sequence is.</p>
<p><strong>2.</strong> Write a function that takes a nucleotide sequence as a string and reverse complements it. Make sure that the function differentiates between DNA input and RNA input. Make sure the output is a DNA string.</p>
<p><strong>3.</strong> Write a for loop that generates five 500 amino acid strings. Make sure to only use the standard 20 AA alphabet.</p>
<ul>
<li><p>Make sure that the strings are <u><strong>NOT</strong></u> identical</p></li>
<li><p>The loop should store each string as an element of a vector named my_fave_proteins (hint: make the vector before the loop).</p></li>
</ul>
<p><strong>4.</strong> Assign the vector my_fave_proteins to an <code>XStringSet</code> object. Name that object my_fave_proteins_set.</p>
<p><strong>5.</strong> Change the first AA of each protein in my_fave_proteins_set to M and give each protein a creative name.</p>
<p><strong>6.</strong> Get the frequency of each AA in each protein stored in my_fave_proteins_set and plot a box plot of the frequency of each AA in all the proteins (plot using <code>ggplot2</code>).</p>
<ul>
<li>Export the plot as PDF</li>
</ul>
<p><strong>7.</strong> Export my_fave_proteins_set as a FASTA file. Name the file yourfirstname_fave_prots.fasta.</p>
<p><strong>8.</strong> Use <code>seqinr</code> to import the first 200 Archaea-associated sequences from <code>genbank</code>. How many Archaeal sequences are there in total?</p>
<p><strong>9.</strong> Assign the imported sequences to an <code>XStringSet</code> object named my_fave_arch_set and reverse complement the sequences.</p>
<ul>
<li>Do not forget to include the sequences’ names</li>
</ul>
<p><strong>10.</strong> What is the length of the longest sequence out of the 200 you imported? Show your work.</p>
<p><strong>11.</strong> Export my_fave_arch_set as a FASTA file. Name the file yourfirstname_fave_arch.fa.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-lab2_intro_to_R_pt2.html" class="pagination-link" aria-label="**Lab 2: Data Manipulation and Presentation in R**">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><strong>Lab 2: Data Manipulation and Presentation in R</strong></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-lab4_biologicaldata2.html" class="pagination-link" aria-label="**Lab 4: Handling of Biological Data in R - 2**">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title"><strong>Lab 4: Handling of Biological Data in R - 2</strong></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/idohatam/Biol3315_lab_book/edit/main/03-lab3_biological_data1.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>